# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-20 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.CharField(max_length=50)),
                ('anio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreComunidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ComunidadLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficios.Comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Depto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numLote', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=50)),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficios.Depto')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numid', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono_f', models.CharField(blank=True, max_length=9, null=True)),
                ('telefono_c', models.CharField(blank=True, max_length=9, null=True)),
                ('es_admin', models.BooleanField(default=False)),
                ('es_secre', models.BooleanField(default=False)),
                ('es_docente', models.BooleanField(default=False)),
                ('es_tutor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Priorizar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.IntegerField()),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficios.Capa')),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficios.Comunidad')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficios.Criterio')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='sexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficios.Sexo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depto',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficios.Pais'),
        ),
        migrations.AddField(
            model_name='comunidadlote',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficios.Lote'),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficios.Municipio'),
        ),
        migrations.AlterUniqueTogether(
            name='comunidadlote',
            unique_together=set([('comunidad', 'lote')]),
        ),
    ]
